rootProject.name = 'echo-standalone-runtime'

include 'echo-runtime-contracts'
include 'echo-runtime-core'
include 'echo-runtime-app'
include 'echo-runtime-client'
include 'echo-runtime-modules'
include 'echo-runtime-packos'
include 'echo-runtime-assets'
include 'echo-runtime-data'
include 'echo-runtime-ui'
include 'echo-runtime-save'
include 'echo-runtime-world'
include 'echo-runtime-entity'
include 'echo-runtime-item'
include 'echo-runtime-gameplay'
include 'echo-runtime-render'
include 'echo-runtime-input'
include 'echo-runtime-player'
include 'echo-runtime-audio'
include 'echo-runtime-network'
include 'echo-runtime-scripting'
include 'echo-runtime-compat'
include 'echo-runtime-testkit'
include 'echo-runtime-devtools'
